config/routes.rb
Rails.application.routes.draw do
  resources :battles
  resources :creatures
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attack.rb
class Attack < ApplicationRecord
  belongs_to :creature, foreign_key: :target_creature_id

  def roll_to_hit
    attack_dice.roll
  end

  def roll_damage
    damage_dice.roll
  end

  def target(creature)
    attack = roll_to_hit

    {
      success: attack >= creature.ac,
      damage: roll_damage
    }
  end

  private

  def attack_dice
    @attack_dice ||= GamesDice.create(dice_roll)
  end

  def damage_dice
    @damage_dice ||= GamesDice.create(dice_roll)
  end
end

app/models/battle.rb
class Battle < ApplicationRecord
end

app/models/creature.rb
class Creature < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  before_action :set_battle, only: %i[ show edit update destroy ]

  # GET /battles or /battles.json
  def index
    @battles = Battle.all
  end

  # GET /battles/1 or /battles/1.json
  def show
  end

  # GET /battles/new
  def new
    @battle = Battle.new
  end

  # GET /battles/1/edit
  def edit
  end

  # POST /battles or /battles.json
  def create
    @battle = Battle.new(battle_params)

    respond_to do |format|
      if @battle.save
        format.html { redirect_to battle_url(@battle), notice: "Battle was successfully created." }
        format.json { render :show, status: :created, location: @battle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @battle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /battles/1 or /battles/1.json
  def update
    respond_to do |format|
      if @battle.update(battle_params)
        format.html { redirect_to battle_url(@battle), notice: "Battle was successfully updated." }
        format.json { render :show, status: :ok, location: @battle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @battle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /battles/1 or /battles/1.json
  def destroy
    @battle.destroy

    respond_to do |format|
      format.html { redirect_to battles_url, notice: "Battle was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_battle
      @battle = Battle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def battle_params
      params.require(:battle).permit(:name, :initiative)
    end
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
  before_action :set_creature, only: %i[ show edit update destroy ]

  # GET /creatures or /creatures.json
  def index
    @creatures = Creature.all
  end

  # GET /creatures/1 or /creatures/1.json
  def show
  end

  # GET /creatures/new
  def new
    @creature = Creature.new
  end

  # GET /creatures/1/edit
  def edit
  end

  # POST /creatures or /creatures.json
  def create
    @creature = Creature.new(creature_params)

    respond_to do |format|
      if @creature.save
        format.html { redirect_to creature_url(@creature), notice: "Creature was successfully created." }
        format.json { render :show, status: :created, location: @creature }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @creature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creatures/1 or /creatures/1.json
  def update
    respond_to do |format|
      if @creature.update(creature_params)
        format.html { redirect_to creature_url(@creature), notice: "Creature was successfully updated." }
        format.json { render :show, status: :ok, location: @creature }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @creature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creatures/1 or /creatures/1.json
  def destroy
    @creature.destroy

    respond_to do |format|
      format.html { redirect_to creatures_url, notice: "Creature was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creature
      @creature = Creature.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def creature_params
      params.require(:creature).permit(:name, :ac, :hp)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/battles_helper.rb
module BattlesHelper
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/views/battles/_battle.html.erb
<div class="container w-full">
  <div class="text-xl font-bold">
    <%= battle.name %>
  </div>

  <div class="bg-gray-200 p-2 text-xs w-full">
    Initiative: <%= battle.initiative %>
  </div>

  <div>
    <h3>Add Combatant</h3>
    Type
    <select class="w-32">
      <value>----</value>
    </select>


    Quantity:
    <input type="number"/>

    <button>Add</button>
  </div>
</div>

app/views/battles/_form.html.erb
<%= form_with(model: battle) do |form| %>
  <% if battle.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(battle.errors.count, "error") %> prohibited this battle from being saved:</h2>

      <ul>
        <% battle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :initiative, style: "display: block" %>
    <%= form.number_field :initiative %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/battles/edit.html.erb
<h1>Editing battle</h1>

<%= render "form", battle: @battle %>

<br>

<div>
  <%= link_to "Show this battle", @battle %> |
  <%= link_to "Back to battles", battles_path %>
</div>

app/views/battles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Battles</h1>

<div id="battles">
  <% @battles.each do |battle| %>
    <%= render battle %>
    <p>
      <%= link_to "Show this battle", battle %>
    </p>
  <% end %>
</div>

<%= link_to "New battle", new_battle_path %>

app/views/battles/new.html.erb
<h1>New battle</h1>

<%= render "form", battle: @battle %>

<br>

<div>
  <%= link_to "Back to battles", battles_path %>
</div>

app/views/battles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @battle %>

app/views/creatures/_creature.html.erb
<div id="<%= dom_id creature %>">
  <p>
    <strong>Name:</strong>
    <%= creature.name %>
  </p>

  <p>
    <strong>Ac:</strong>
    <%= creature.ac %>
  </p>

  <p>
    <strong>Hp:</strong>
    <%= creature.hp %>
  </p>

</div>

app/views/creatures/_form.html.erb
<%= form_with(model: creature) do |form| %>
  <% if creature.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(creature.errors.count, "error") %> prohibited this creature from being saved:</h2>

      <ul>
        <% creature.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :ac, style: "display: block" %>
    <%= form.number_field :ac %>
  </div>

  <div>
    <%= form.label :hp, style: "display: block" %>
    <%= form.number_field :hp %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/creatures/edit.html.erb
<h1>Editing creature</h1>

<%= render "form", creature: @creature %>

<br>

<div>
  <%= link_to "Show this creature", @creature %> |
  <%= link_to "Back to creatures", creatures_path %>
</div>

app/views/creatures/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Creatures</h1>

<div id="creatures">
  <% @creatures.each do |creature| %>
    <%= render creature %>
    <p>
      <%= link_to "Show this creature", creature %>
    </p>
  <% end %>
</div>

<%= link_to "New creature", new_creature_path %>

app/views/creatures/new.html.erb
<h1>New creature</h1>

<%= render "form", creature: @creature %>

<br>

<div>
  <%= link_to "Back to creatures", creatures_path %>
</div>

app/views/creatures/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @creature %>

<div>
  <%= link_to "Edit this creature", edit_creature_path(@creature) %> |
  <%= link_to "Back to creatures", creatures_path %>

  <%= button_to "Destroy this creature", @creature, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chucker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>